### ISSUE TITLE
Missing ApiVersion parameter for SubscriptionClient

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#91]
https://github.com/Azure/autorest.testserver/blob/a5e6e2ef725df87c8981116836531a2f10be9128/swagger/subscriptionId-apiVersion.json#L34

ApiVersion is missing in the parameter list

![image](https://user-images.githubusercontent.com/1050156/70840122-1ec1c680-1dc5-11ea-8062-e1574c2f2a2d.png)

There is 3 parameters: subscription id, RG name and $host, but no api-version

**Comment by fearthecowboy** [comment]
It should be fixed now -- 

https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/scenarios/subscriptionId-apiVersion/modeler.yaml#L195

**Comment by lmazuel** [comment]
@fearthecowboy I don't understand, I still have only 3 parameters :(

**Comment by lmazuel** [comment]
Garrett, file was generated mid-december, maybe a regression?

**Comment by fearthecowboy** [comment]
Hmm. Oh, requires a newer version of autorest core too. I published .6184 earlier today. That should have the part that fixes that in it.

The was fixed back in December, and IIRC it was in the core.

**Comment by lmazuel** [comment]
@fearthecowboy it's wgat I used :(
```
version: 3.0.6184
use-extension:
  "@autorest/modelerfour": "4.2.106"
```

**Comment by fearthecowboy** [comment]
*sigh*

Apparently the last half of that was in the PR I had in this morning, that is now done publishing.

2.0.108 

# this time for sure
https://github.com/Azure/autorest.modelerfour/blob/f80448d1bbabcf764bdee2957c6d5ef012f9aa9e/modelerfour/test/scenarios/subscriptionId-apiVersion/modeler.yaml#L184-L199

**Comment by lmazuel** [comment]
@fearthecowboy So the fun part is I still don't get it, however I get diff in BodyComplex / Validation with a new parameter api_version (that I didn't expect). I need to dig a little more, but still missing the one I need in SubscriptionId client :(

```
version: 3.0.6184
use-extension:
  "@autorest/modelerfour": "4.2.108"
```

**Comment by lmazuel** [comment]
@fearthecowboy still don't have it. Good news is the diff on complex/validation I was mentionning is correct
```
version: 3.0.6185
use-extension:
  "@autorest/modelerfour": "4.3.121"
```
autorest-beta 3.0.6149

**Comment by lmazuel** [comment]
Fixed with 4.9
